server:
  port: 9090
  use-forward-headers: true
  session:
    cookie:
      http-only: true
  contextPath: /fhir
  servlet:
    context-path: /fhir


spring:
  application:
    name: fhir
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

swagger:
  enable: true
  basePackage: com.ha.fhir

hapi:
  fhir:
    serverbase: http://hapi-fhir.apjcorp.com/fhir
